# Generated by Django 3.2.18 on 2023-03-25 13:37

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_alfacrm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alfacrmuser",
            name="password",
            field=models.CharField(
                help_text="Придумайте пароль",
                max_length=150,
                verbose_name="Пароль пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="alfacrmuser",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username "
                              "already exists."
                },
                help_text="Required. 150 characters or fewer. "
                          "Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=False,
                validators=[
                    django.contrib.auth.validators.UnicodeUsernameValidator()
                    ],
                verbose_name="username",
            ),
        ),
    ]
