# Generated by Django 3.2.18 on 2023-04-04 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_alfacrm", "0003_auto_20230327_1827"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alfacrmuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
