# Generated by Django 3.2.18 on 2023-04-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_alfacrm", "0005_auto_20230410_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="alfacrmuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
