# Generated by Django 3.2.18 on 2023-04-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_alfacrm", "0006_auto_20230411_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alfacrmuser",
            name="referral_code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
