# Generated by Django 3.2.18 on 2023-04-13 04:59

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_alfacrm", "0007_auto_20230412_0608"),
    ]

    operations = [
        migrations.AddField(
            model_name="alfacrmuser",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
