# Generated by Django 3.2.18 on 2023-04-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_alfacrm", "0008_auto_20230413_0459"),
    ]

    operations = [
        migrations.AddField(
            model_name="alfacrmuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="Аватарка"
            ),
        ),
    ]
