# Generated by Django 3.2.18 on 2023-05-02 06:45

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_alfacrm', '0010_auto_20230424_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinaties',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                        )
                ),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                        )
                ),
                ('district', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                (
                    'coordinaties', models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='users_alfacrm.coordinaties'
                        )
                ),
            ],
        ),
        migrations.AddField(
            model_name='alfacrmuser',
            name='city',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='users_alfacrm.city'
            ),
        ),
    ]
