# Generated by Django 3.2.18 on 2023-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_alfacrm', '0012_auto_20230517_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfacrmuser',
            name='firebase_token',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name='Firebase токен'
            ),
        ),
    ]
