# Generated by Django 3.2.18 on 2023-03-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название курса",
                        max_length=200,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Укажите описание курса",
                        verbose_name="Описание курса",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("EN", "Английский язык"),
                            ("ME", "Тренировка памяти"),
                            ("RO", "Робототехника"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preview", models.ImageField(upload_to="previews/")),
                (
                    "duration",
                    models.DurationField(
                        help_text="Укажите длительность видео",
                        verbose_name="Длительность видео",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Укажите ссылку на видео",
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество баллов, "
                                  "которое будет начисляться",
                        verbose_name="Количество баллов",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("viewed", models.BooleanField(default=False)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_videos",
                        to="courses.video",
                    ),
                ),
            ],
        ),
    ]
