# Generated by Django 3.2.18 on 2023-03-27 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео"},
        ),
    ]
