# Generated by Django 3.2.18 on 2023-04-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_auto_20230331_0808"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="promo_video",
        ),
        migrations.AddField(
            model_name="coupon",
            name="partner_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Название компании партнера",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="courses.partner",
            ),
        ),
    ]
