# Generated by Django 3.2.18 on 2023-04-04 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0005_auto_20230404_0412"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservideo",
            name="user_id",
        ),
        migrations.AddField(
            model_name="uservideo",
            name="partner_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.partnervideo",
            ),
        ),
        migrations.AddField(
            model_name="uservideo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_alfacrm.alfacrmuser",
            ),
            preserve_default=False,
        ),
    ]
