# Generated by Django 3.2.18 on 2023-04-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_auto_20230404_0659"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercoupon",
            options={
                "verbose_name": "Купон пользователя",
                "verbose_name_plural": "Купоны пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="uservideo",
            options={
                "verbose_name": "Просмотренное видео",
                "verbose_name_plural": "Просмотренные видео",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
