# Generated by Django 3.2.18 on 2023-04-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_auto_20230405_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="coupon_type",
            field=models.CharField(
                choices=[("own", "Свой"), ("partner", "Партнерский")],
                default="own",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.course",
            ),
        ),
    ]
