# Generated by Django 3.2.18 on 2023-04-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_auto_20230407_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(
                default=1,
                help_text="Укажите описание урока",
                verbose_name="Описание урока",
            ),
            preserve_default=False,
        ),
    ]
