# Generated by Django 3.2.18 on 2023-04-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_auto_20230417_1718"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercoupon",
            name="redeemed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время получения купона"
            ),
        ),
    ]
