# Generated by Django 3.2.18 on 2023-05-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_usercoupon_redeemed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='video_coupone',
            field=models.ForeignKey(
                blank=True,
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='coupone_videos',
                to='courses.video'
            ),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(
                help_text='Укажите описание видео',
                verbose_name='Описание видео'
            ),
        ),
    ]
