# Generated by Django 3.2.18 on 2023-05-17 16:06

from datetime import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0015_auto_20230503_1449"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "Направление курсов",
                "verbose_name_plural": "Направления курсов",
            },
        ),
        migrations.AlterModelOptions(
            name="partner",
            options={
                "verbose_name": "Партнер и промо-видео партнера",
                "verbose_name_plural": "Партнеры и промо-видео партнеров",
            },
        ),
        migrations.AlterModelOptions(
            name="usercoupon",
            options={
                "verbose_name": "Купон пользователя",
                "verbose_name_plural": "Купоны пользователей и "
                                       "списание баллов за купоны",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={
                "verbose_name": "Видео для курсов и купонов Нейроленда",
                "verbose_name_plural": "Видео для курсов и купонов Нейроленда",
            },
        ),
        migrations.AddField(
            model_name="direction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime(2023, 1, 1)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_type",
            field=models.CharField(
                choices=[("own", "Свой"), ("partner", "Партнерский")],
                help_text="Выберите тип купона: Свой - "
                          "Нейроленда или Партнерский",
                max_length=255,
                verbose_name="Тип купона",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполните это поле, если купон партерский",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="courses.partner",
                verbose_name="Партнер",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="partner_name",
            field=models.CharField(
                blank=True,
                help_text="Заполните это поле, если купон партерский",
                max_length=255,
                null=True,
                verbose_name="Название компании партнера",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="title",
            field=models.CharField(
                help_text="Укажите название купона",
                max_length=255,
                verbose_name="Название купона",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="video_coupone",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполните это поле, если купон свой - Нейроленда",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupone_videos",
                to="courses.video",
                verbose_name="Видео для своего купона",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="video_coupone_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполните это поле, если купон партерский",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupone_videos",
                to="courses.partnervideo",
                verbose_name="Видео для партнерского купона",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="direction",
            field=models.ForeignKey(
                help_text="Выберите направление",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.direction",
                verbose_name="Направление",
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="name",
            field=models.CharField(
                help_text="Укажите название направления",
                max_length=200,
                verbose_name="Название направления",
            ),
        ),
        migrations.AlterField(
            model_name="partnervideo",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.partner",
                verbose_name="Партнер",
            ),
        ),
        migrations.AlterField(
            model_name="partnervideo",
            name="partner_preview",
            field=models.ImageField(
                help_text="Добавьте превью-картинку",
                upload_to="partners_previews/",
                verbose_name="Превью видео",
            ),
        ),
        migrations.AlterField(
            model_name="partnervideo",
            name="points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество баллов, которое "
                          "будет начисляться за просмотр",
                verbose_name="Количество баллов",
            ),
        ),
        migrations.AlterField(
            model_name="partnervideo",
            name="promo_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на промо-видео партнера",
                null=True,
                verbose_name="Ссылка на промо-видео партнера",
            ),
        ),
        migrations.AlterField(
            model_name="usercoupon",
            name="coupon",
            field=models.ForeignKey(
                help_text="Выберите купон",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coupon",
                verbose_name="Купон",
            ),
        ),
        migrations.AlterField(
            model_name="usercoupon",
            name="user",
            field=models.ForeignKey(
                help_text="Укажите клиента, которому хотите добавить купон",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Если это видео урок, то укажите, "
                          "к какому курсу относится видео",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="points",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество баллов, которое "
                          "будет начисляться за просмотр видео",
                verbose_name="Количество баллов",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="preview",
            field=models.ImageField(
                help_text="Добавьте превью-картинку",
                upload_to="previews/",
                verbose_name="Превью видео",
            ),
        ),
    ]
